deriv-com/perl-Myriad

cpanfile, lib/Myriad/Service/Storage.pm, lib/Myriad/Service/Storage/Remote.pm, lib/Test/Myriad.pm, t/commands.t, t/myriad.t, t/registry.t
Object::Pad version 0.38 added officially-documented ways to obtain the metaclass for a given class, replacing the "words in practice" but undocumented `->META` internal implementation detail. These should be used instead for future compatibility.
=> Use officially documented way to obtain Object::Pad's metaclasses

lib/Myriad/Config.pm, t/config.t, t/config.yml
We have some cases where words are allowed in singular or plural form, which is extremely problematic for code maintenance:
- `instance`
- `service`
- `config`
These should be consistently singular throughout the codebase and config files.
=> Standardise on singular terminology

Changes, README.md, cpanfile, lib/Myriad/RPC/Implementation/Memory.pm
With Future::XS, the `Future` package will end up pushing most of the work over to inherited methods. This causes direct function calls such as `Future::wait_any` to fail (should be `Future->wait_any` instead). Fixes test failures seen in Future `0.48_001`.
=> Fix usage of Future helpers

cpanfile
Since we use `->add_method`, the bug fix in https://rt.cpan.org/Public/Bug/Display.html?id=144975 is relevant: anyone calling `->can()` in services could get confusing results with the previous version.
=> Update Object::Pad for a very minor bugfix

Changes, cpanfile, lib/Myriad/Transport/Redis.pm
Use [Net::Async::Redis::XS](https://metacpan.org/pod/Net::Async::Redis::XS) if installed _and_ the `PERL_REDIS_XS` environment variable is set.
=> Support for faster Redis implementation

Changes, lib/Myriad/Config.pm, lib/Myriad/Transport/Redis.pm
Configuration updates had two mechanisms for notifying the Myriad::Config observables on change:
- clientside cache key tracking
- keyspace notifications
The keyspace notifications were failing due to an incorrect assumption about the returned object, and this failure was hidden by a log message which left out the exception details.
=> Fix Redis keyspace notifications for Myriad::Config

lib/Myriad/Class.pm
Currently, this:
```perl
package Example;
use Deriv::Class extends => qw(Some::Parent);
```
will not load `Some::Parent` automatically, and this can lead to some peculiar and hard-to-trace errors. Since we're loading modules in other cases, we should be doing this for `extends` as well.
=> The `extends` option should load the module if not already available

LICENSE
The content of the Perl artistic license file was reformatted in recent versions of Software::License, specifically https://metacpan.org/release/LEONT/Software-License-0.104004/source onwards.
This causes `dzil build` to show local version control changes, so the purpose of this PR is to bring that up to date with the current CPAN version.
=> dzil build with latest Software::License installed

cpanfile
There have been [performance improvements](https://metacpan.org/release/PEVANS/Object-Pad-0.803/source/Changes) in Object::Pad object creation, various fixes and improvements to Redis cluster handling plus the latest 7.2 command list (https://metacpan.org/release/TEAM/Net-Async-Redis-4.000/source/Changes), and syntax improvements for the operators and match/case modules as well.
=> Update to latest CPAN modules

lib/Myriad.pm
Similar to 7fdc4d6d75619536596eb88d9ac9028df64a0ec6, this provides some basic protection against reüse of these Futures when the `->without_cancel` versions are needed.
=> Ensure `$run` and `$shutdown` Futures don't end up cancelled

lib/Myriad/API.pm, lib/Myriad/Mutex.pm, lib/Myriad/Registry.pm, lib/Myriad/Role/Storage.pm, lib/Myriad/Service/Implementation.pm, lib/Myriad/Storage/Implementation/Memory.pm, lib/Myriad/Storage/Implementation/Redis.pm, lib/Myriad/Transport/Redis.pm, lib/Myriad/Util/Defer.pm, t/storage.t
Extracting out the `$api->mutex` method from https://github.com/deriv-com/perl-Myriad/pull/300.
This provides a basic mutex-with-timeout primitive which can be used to ensure only one worker is actively running the code block at a time.
It's mainly intended for multiple-worker API calls and database operations where we don't want to flood third-party APIs with requests from multiple active workers, but _do_ want basic high-availability handling in case some workers run into problems.
=> Mutex support

lib/Myriad/Service/Remote.pm, lib/Myriad/Service/Remote/RPC.pm
Instead of:
```perl
$srv->call_rpc(method_name => ...);
```
it looks more consistent with the rest of the code to be doing this:
```perl
$srv->method_name(...)
```
and with introspection we'll be able to construct classes and provide "method not found" semantics later this way.
=> Provide a proxy class to make method calls neater

lib/Myriad/Subscription/Implementation/Redis.pm
Current behaviour is to attempt cleanup only when we hit the pending subscription item limit.
That causes regular delays in highly-active streams, so we change that behaviour here to check earlier; currently this happens when we hit 75% of the backlog capacity. If we can remove old items before we hit the limit, that reduces the chances of the `:Emitter` having to pause.
=> Clean up before we hit the stream limit

lib/Myriad/Subscription/Implementation/Redis.pm
Although the previous version worked, we're expecting to extend the logic here (subscription introspection, potentially async/threaded compression, and notification channels), so this really needs to be an `async` method to support that.
=> Since we have await calls in here, switch to async method

lib/Myriad/Role/Storage.pm, lib/Myriad/Storage/Implementation/Memory.pm, lib/Myriad/Storage/Implementation/Redis.pm
To complement the ordered set handling, we'd want support for unordered sets. This adds those to the memory and Redis implementations with an `unorderedset_` prefix, makes them slightly verbose to type but hopefully clear enough.
In Redis, these are backed by `SADD`, `SREM` etc., see https://redis.io/docs/latest/commands/?group=set for more details.
=> Support for unordered set methods

lib/Myriad/Storage/Implementation/Memory.pm, lib/Myriad/Storage/Implementation/Redis.pm
Redis and other backends tend to support multiple key/value pairs, which is more efficient than setting one value at a time in a larger hash structure. We add support for this by allowing either single `key => value`, or a hashref (with no value).
=> Support for passing hashref to ->hash_set

lib/Myriad/Role/Storage.pm, lib/Myriad/Storage/Implementation/Memory.pm, lib/Myriad/Storage/Implementation/Redis.pm
Adds the `list_range` method, which takes start and end index for returning multiple items from a list.
=> Support for list range storage method

lib/Myriad/Role/Storage.pm, lib/Myriad/Storage/Implementation/Memory.pm, lib/Myriad/Storage/Implementation/Redis.pm
This adds a method for returning the current number of items in a list in storage.
=> Support for `list_count` storage method

cpanfile
The header files can no longer be found by dependent modules, e.g. Syntax::Keyword::Match, due to this change:
```
* Use `File::ShareDir` for storing .h include files, rather than
storing the contents in the `__DATA__` section of the build helpers
```
Pinning to a working version for now.
Symptoms are errors such as these in `cpanm` installation logs:
```
lib/Syntax/Keyword/Match.xs:18:10: fatal error: hax/perl-backcompat.c.inc: No such file or directory
18 | #include "hax/perl-backcompat.c.inc"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
=> Pin XS::Parse::Keyword to working version, due to 0.43 breakage

lib/Myriad/Class.pm, lib/Myriad/Storage/Implementation/Memory.pm, lib/Myriad/Storage/Implementation/Redis.pm
Support signature format for earlier Perl versions which did not yet have `//=`. We only want to provide a default here when there's no parameter supplied, technically `//= undef` doesn't make much sense anyway.
=> Backward compatibility for perl 5.36.0

lib/Myriad/RPC/Implementation/Redis.pm, lib/Myriad/Transport/Redis.pm
When deploying a new service, there's a check for pending messages on all RPC queues - looking for items that have been started but not acknowledged by the previous consumer (i.e. process died before they completed).
Since those streams don't exist yet, this was displaying a warning:
> Could not read pending messages on stream: `myriad.service.example.service.rpc/warning_sample` | error: NOGROUP No such key '`myriad.service.example.service.rpc/warning_sample`' or consumer group 'processors' at .../Net/Async/Redis/Cluster.pm line 691.
Although harmless, this happens frequently enough to be distracting, and technically shouldn't happen: we should always create our streams first before trying to do anything with them. This change applies the pending check after stream creation.
=> Ensure our RPC/subscription group exists before we check for pending messages

lib/Myriad/RPC/Client/Implementation/Memory.pm, lib/Myriad/RPC/Client/Implementation/Redis.pm, lib/Myriad/RPC/Implementation/Redis.pm, lib/Myriad/Service/Implementation.pm, lib/Myriad/Subscription/Implementation/Memory.pm, lib/Myriad/Subscription/Implementation/Redis.pm
Applies some improvements to our initial pending-message-claim sequence, and how we deal with exceptions thrown by various related paths.
=> Fix RPC pending queue error handling

lib/Myriad/Class.pm, lib/Myriad/Service/Implementation.pm, lib/Myriad/Subscription/Implementation/Memory.pm, lib/Myriad/Subscription/Implementation/Redis.pm
Avoid loading or calling OpenTelemetry unless explicitly enabled, e.g. via
```
USE_OPENTELEMETRY=1 myriad.pl ...
```
This is due to stability problems relating to `dynamically` and cancellation/exception handling: especially on recent versions of Perl, we're seeing various memory corruption issues. Since this is supposed to be an opt-in feature, due to performance hit and that it's not useful without the OpenTelemetry endpoint and infrastructure available, disabling by default was the intended direction anyway.
Symptoms include:
```
Attempt to free unreferenced scalar: SV 0x5603c40210f8 at /opt/perl-5.40.0/lib/site_perl/5.40.0/OpenTelemetry/Context.pm line 9.
```
and segmentation faults.
This change attempts to bypass OpenTelemetry (including module load) unless the `USE_OPENTELEMETRY` …
=> Only enable OpenTelemetry when explicitly requested

lib/Myriad/Exception/Builder.pm, lib/Test/Myriad.pm, t/define_role.t, t/role.t
Turning on _everything_ considered harmful, see Github issue #334 for an example of this.
=> Only enable the specific Object::Pad experimental features we need

lib/Myriad/API.pm, lib/Myriad/Transport/Redis.pm
This allows a service to have multiple independent mutex instances, for example per emitter or RPC call. The default is still a per-service mutex.
=> Support `key` parameter in `$api->mutex`

lib/Myriad/Transport/Redis.pm
When multiple workers start up at the same time, the create-group-then-delete-it logic needed for Redis stream creation can end up interleaved, e.g. two CREATEs then two DESTROYs. Redis will dutifully throw an error at that point because you asked it to delete something which has already gone.
In our case, that's fine - we only need to clean up the unused group, we don't care who deleted it.
=> Handle stream creation race condition

lib/Myriad/Mutex.pm
Even if we have not yet been notified that the key is free, we check again. There are cases where the notification channel may not deliver the key-changed event, for example if we had a Redis server migration while waiting.
We also add a check for mutex-locked-on-exit so we can issue a warning about it.
=> Re-try mutex acquisition periodically

lib/Myriad/Class.pm
This has started to throw exceptions when called with unexpected parameters. The fix here is to avoid passing the package - it was previously ignored, and does not do anything useful in the new versions either.
https://metacpan.org/release/PEVANS/XS-Parse-Sublike-0.29/changes
=> Sublike::Extended as of 0.29+ checks for unexpected parameters

lib/Myriad/Service/Implementation.pm
Previously, this would take a snapshot of all the RPC method coderefs, and use those when handling any incoming RPC calls.
The downside of this approach is that it leads to surprising behaviour if you try to override the RPC method with something else later, for example in a method attribute.
We don't really gain anything by doing this - Perl already caches method calls. This commit therefore changes the behaviour to a standard method call keyed by the method name, meaning each RPC call will use whichever method is in the package symbol table.
=> Use current instance method for RPC calls

lib/Myriad/Role/Storage.pm, lib/Myriad/Storage/Implementation/Memory.pm, lib/Myriad/Storage/Implementation/Redis.pm, lib/Myriad/Transport/Redis.pm
New storage methods for key and hash key expiry:
- `expire` - marks this item (any type) for expiry after the given number of seconds, use -1 to expire immediately and 0 to disable expiry (keep it forever)
- `hash_expire` - marks this hash key for expiry, as above use -1 to expire immediately and 0 to mark as persistent; hash keys can be provided as a single value or an arrayref of values
=> Support for expiry on storage items and hash keys

lib/Myriad/Role/Storage.pm, lib/Myriad/Storage/Implementation/Memory.pm, lib/Myriad/Storage/Implementation/Redis.pm, lib/Myriad/Transport/Redis.pm
Support for item removal from hashes. The `->hash_remove` method removes a key previously set via `->hash_set`, and can take an arrayref of hash keys if multiple items need to be removed at once.
=> Provide ->hash_remove storage method

lib/Myriad/RPC/Client/Implementation/Memory.pm, lib/Myriad/RPC/Client/Implementation/Redis.pm, t/RPC/full-cycle.t
If an RPC call fails, the details are placed in the `error` response.
If we're using `->call_rpc` or other wrapper mechanisms, we want those to fail in those cases, so this adds a check for the `{error}` key and uses that to construct an `InternalException` instance. Note that the precise details of the exception are likely to change to accommodate the interoperability requirements for other languages: ideally we'd always raise the same exception class and details as the upstream service threw, but also need to be careful about the following cases:
- custom code in the exception object that isn't available on the caller
- internal errors which should be distinguishable from application errors
For these reasons, we start with an `InternalException` instance in all cases, since we expect …
=> Rethrow exceptions across RPC boundary

lib/Myriad/API.pm, lib/Myriad/Service/Bus.pm, lib/Myriad/Service/Remote.pm, lib/Myriad/Service/Remote/Bus.pm, lib/Myriad/Transport/Redis.pm, lib/Test/Myriad/Service.pm, t/service-bus.t
This adds a `->bus` method for lightweight notifications between services. It uses the Redis sharded pub/sub mechanism to send notifications between services.
=> Provide event bus for services

lib/Myriad/RPC/Implementation/Redis.pm, lib/Myriad/Transport/Redis.pm
As the number of RPC methods increases, we run into issues with the current setup which does a blocking `XREADGROUP`.
Since we have clientside caching available, we can use this to deliver a "stream has new items" event, avoiding the need to block. We trigger this notification by making an `xstream info` call, since `xreadgroup` itself doesn't mark the key as being read.
=> Convert blocking RPC streams XREADGROUP to event-driven polling

lib/Myriad/RPC/Client/Implementation/Redis.pm, lib/Myriad/Transport/Redis.pm
As part of the service bus support, more places are using the `->subscribe` method on the transport. Unfortunately this means that we had some inconsistencies between callers expecting a `Net::Async::Redis::Subscription` instance, and other places just expecting a `Ryu::Source` with the event payloads.
Since this is supposed to be transport-agnostic, we standardise on the latter: `->subscribe` now returns a `Ryu::Source` with the `->payload` event stream in both cases.
=> Bug fix: subscribe method should return the payload stream

lib/Myriad/Storage/Implementation/Redis.pm, lib/Myriad/Transport/Redis.pm
Previous versions had unnecessarily-verbose logging when we receive these events. This has been downgraded to `trace` level.
Additionally, the key prefixes were inconsistent, partly due to functionality duplicated between the storage and transport subsystems.
=> Some fixes and cleanup for `->when_key_changed` storage method

lib/Myriad/API.pm
Sometimes a service may need to know its defined name, for example when interacting with external APIs or monitoring.
We now make this available via `$api->service_name`.
=> Provide `->service_name` accessor via `$api`
